### ISSUE TITLE
Model charging 

### ISSUE THREAD

**Issue by Ajay0459** [illusion0001/PS4-RDR2-Havana-Mod-Menu-Releases#1]
When I change my model It changes back after closing the menu

**Comment by illusion0001** [comment]
😭 I'll find a fix for it. I changed it to disable this model changer because it causes infinite loading screen for mission replay

**Comment by illusion0001** [comment]
Fixed in [v1.1](https://github.com/illusion0001/PS4-RDR2-Havana-Mod-Menu-Releases/releases/tag/v1.10)
